### ISSUE TITLE
Default Address?

### ISSUE THREAD

**Issue by BoBeR182** [gdassori/gangsta#1]
Address: 141zGWjsJhnvzjPQsRVKYM6VPsmv9yPYVR

Who does this address belong to and can I replace it with my own?

**Comment by gdassori** [comment]
Thank you for your feedback,

as far as I can see is an address I previously used for mock, but it's just in the default HTML view, and actually you wouldn't see it, since it should be replace by the keys you imported. 
Where you see this address? Did you see it on the app or you was just inspecting the code?

To be sure I've tested gangsta again and works properly, here the address doesn't affect in any way the app.

Anyway, I'm removing this mock address from the source, and I'll remove it on the online demo as well asap.

**Comment by BoBeR182** [comment]
Just checking out the source code.

**Comment by gdassori** [comment]
Ah ok cool :-)
