### ISSUE TITLE
Where do I replace blockr info.

### ISSUE THREAD

**Issue by BoBeR182** [gdassori/gangsta#2]
I try running my own version on my self hosted platform, but the imported private keys never display an updated balance from blockr.

**Comment by BoBeR182** [comment]
![screenshot from 2015-03-16 07 08 37](https://cloud.githubusercontent.com/assets/525433/6665115/4968ed8e-cbac-11e4-9bdb-83d432eae66d.png)
Stuck like this.

**Comment by gdassori** [comment]
Issue should be resolved, please pull.
Keep in mind that everything is experimental, something not tested enough (online I kept an early version cause of this) and I'm not responsible if you, let's say, spend 0.1 BTC in fees because of some code mistake :-p
Use it as a plenty-of-bugs proof of concept and feel free to stage fixes.

**Comment by BoBeR182** [comment]
ReferenceError: wallet_service is not defined app.js:128:4

**Comment by gdassori** [comment]
Are you using Firefox?
Looks like requirejs has problems with Firefox (or, at least, the way I've implemented it doesn't work with Firefox), I wasn't aware. 
Please use Chrome or Chromium, I'll work on this.

Something unrelated: I'm seeing you're importing a single private key. 
By design, to edit the transaction, gangsta needs to know the change address private key, or it wont work.

**Comment by BoBeR182** [comment]
Yes I am using latest version of Firefox, I assumed gangsta would send the change to itself.

**Comment by gdassori** [comment]
Mhm, try, but at the moment I guess it will fail in some way if you don't have a change address and a recipient, so at least 2 outputs.

**Comment by gdassori** [comment]
Fix from BoBer182 tested on Firefox and merged.
